name: Build

on:
  push:
    branches: [ main ]
    paths:
      - src/**
      - package-lock.json
      - action.yml
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: script/bootstrap
        run: script/bootstrap

      - name: script/cibuild
        run: script/cibuild

      - name: Update README
        run: script/update-readme

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          commit-message: Update build
          title: Update build